name: Post Sample Lock Report

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    strategy:
      matrix:
        format:
          - simple
          - table
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - name: Run
        id: report
        run: |
          uv sync

          uv run script/test-action.py --output-format ${{ matrix.format }}
          sed -i 's/uv Lockfile Report/Sample Lockfile Report - ${{ matrix.format }}/g' report.json
          echo report=$(cat report.json) >> "$GITHUB_OUTPUT"

      - name: Post a comment to the PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            // Find existing report comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const lockReportComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('<!-- ${{ matrix.format }}-lockfile-report -->')
              });
            // Delete existing report comments
            if (lockReportComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: lockReportComment.id,
              });
            }
            // Post new report comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<!-- ${{ matrix.format }}-lockfile-report -->\n${{ fromJSON(steps.report.outputs.report).markdown }}`
            })
